<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SRAVAN-PC" failures="2" tests="12" name="com.lamdatest.tests.LamdaAssesmentTest" time="318.870" errors="0" timestamp="21 Jan 2024 14:36:26 GMT">
  <testcase classname="com.lamdatest.tests.LamdaAssesmentTest" name="Scenario_1Test" time="18.684"/>
  <testcase classname="com.lamdatest.tests.LamdaAssesmentTest" name="Scenario_1Test" time="32.674"/>
  <testcase classname="com.lamdatest.tests.LamdaAssesmentTest" name="Scenario_1Test" time="41.203"/>
  <testcase classname="com.lamdatest.tests.LamdaAssesmentTest" name="Scenario_3Test" time="65.961"/>
  <testcase classname="com.lamdatest.tests.LamdaAssesmentTest" name="Scenario_1Test" time="15.776"/>
  <testcase classname="com.lamdatest.tests.LamdaAssesmentTest" name="Scenario_3Test" time="39.410"/>
  <testcase classname="com.lamdatest.tests.LamdaAssesmentTest" name="Scenario_3Test" time="12.188">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.lamdatest.tests.LamdaAssesmentTest.Scenario_3Test(LamdaAssesmentTest.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- Scenario_3Test -->
  <testcase classname="com.lamdatest.tests.LamdaAssesmentTest" name="Scenario_2Test" time="17.989"/>
  <testcase classname="com.lamdatest.tests.LamdaAssesmentTest" name="Scenario_2Test" time="24.562"/>
  <testcase classname="com.lamdatest.tests.LamdaAssesmentTest" name="Scenario_3Test" time="22.324"/>
  <testcase classname="com.lamdatest.tests.LamdaAssesmentTest" name="Scenario_2Test" time="16.118"/>
  <testcase classname="com.lamdatest.tests.LamdaAssesmentTest" name="Scenario_2Test" time="11.981">
    <failure message="expected [95] but found [51]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [95] but found [51]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.lamdatest.tests.LamdaAssesmentTest.Scenario_2Test(LamdaAssesmentTest.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- Scenario_2Test -->
</testsuite> <!-- com.lamdatest.tests.LamdaAssesmentTest -->
